// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb65M-HkAMwHrZLHBpd929eHN62L2rIPo',
    appId: '1:590129396378:web:659f8ac54649913db13d23',
    messagingSenderId: '590129396378',
    projectId: 'walky-8604a',
    authDomain: 'walky-8604a.firebaseapp.com',
    storageBucket: 'walky-8604a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmYCMOrqbKwjQ8pLNgzKZE1V0IXhY5cU8',
    appId: '1:590129396378:android:8d59b34f9635a4f8b13d23',
    messagingSenderId: '590129396378',
    projectId: 'walky-8604a',
    storageBucket: 'walky-8604a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPYa9Qexpx4H_8Oum7wgEAz8P_sv70hxc',
    appId: '1:590129396378:ios:b127fb4edafb0e0cb13d23',
    messagingSenderId: '590129396378',
    projectId: 'walky-8604a',
    storageBucket: 'walky-8604a.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPYa9Qexpx4H_8Oum7wgEAz8P_sv70hxc',
    appId: '1:590129396378:ios:b127fb4edafb0e0cb13d23',
    messagingSenderId: '590129396378',
    projectId: 'walky-8604a',
    storageBucket: 'walky-8604a.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb65M-HkAMwHrZLHBpd929eHN62L2rIPo',
    appId: '1:590129396378:web:a30adf450d881f49b13d23',
    messagingSenderId: '590129396378',
    projectId: 'walky-8604a',
    authDomain: 'walky-8604a.firebaseapp.com',
    storageBucket: 'walky-8604a.firebasestorage.app',
  );
}
